version: '3.8'

services:
  # 크롤러 서비스 (단발성 실행)
  crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: crawler-service
    environment:
      # 외부 MongoDB URI 설정 (환경변수로 제공)
      CRAWLER_SERVICE_MONGODB_URI: ${CRAWLER_SERVICE_MONGODB_URI:-mongodb://localhost:27017/job_crawler}
      LOG_LEVEL: INFO
      TZ: Asia/Seoul
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
    network_mode: host  # 로컬 MongoDB 접근을 위해
    # 단발성 실행 후 종료
    restart: "no"

  # 주기적 실행용 크롤러 (별도 서비스)
  crawler-cron:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: crawler-cron-service
    environment:
      CRAWLER_SERVICE_MONGODB_URI: ${CRAWLER_SERVICE_MONGODB_URI:-mongodb://localhost:27017/job_crawler}
      LOG_LEVEL: INFO
      TZ: Asia/Seoul
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./crontab:/etc/cron.d/crawler-cron:ro
    network_mode: host  # 로컬 MongoDB 접근을 위해
    restart: unless-stopped
    # cron 실행을 위한 명령어 오버라이드
    command: >
      bash -c "
        # 크론탭 등록
        crontab /etc/cron.d/crawler-cron
        # 크론 서비스 시작
        service cron start
        # 로그 파일 생성
        touch /app/logs/cron.log
        # 무한 루프로 컨테이너 유지
        tail -f /app/logs/cron.log
      "